config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homepage#home"

  # get "/home", to: "homepage#home"
  get "/login", to: "homepage#login"
  get "/signin", to: "homepage#signin"

  resources :users, only: [:new, :create, :index, :show]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    # Risolto solo se, nel form di registrazione la pass corrisponde alla conferma pass
    # :password_confirm viene permesso come parametro ma non sarà salvato nel DB
    validates :password, :confirmation => true
    validates :password_confirmation, :presence => true

    def welcome
        "Hello, #{self.username}!"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # The before_action filter is called before the specified actions. 
    # In our case it will be called on all actions whose controller inherit from our application controller.
    before_action :require_login

    # Permette di ottenere l'utente attualemente loggato
    helper_method :current_user

    def require_login
      redirect_to new_session_path unless session.include? :user_id
    end

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  skip_before_action :require_login, only: [:home]

  def home
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # Non richiede login prima delle action Create e New, before_action applicato in application_controller
  skip_before_action :require_login, only: [:create, :new]

  def new
  end

  def create
    session_params = params.permit(:username, :password)
    @user = User.find_by(username: session_params[:username])
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = "Email o Password errate!"
      redirect_to new_session_path
    end
  end

  def destroy
    # Rimuove user id dalla sessione corrente dopo il logout
    session[:user_id] = nil
    # Messaggio di logout
    flash[:notice] = "You have been signed out!"
    # Reindirizza alla homepage
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # Non richiede login prima delle action Create e New, before_action applicato in application_controller
    skip_before_action :require_login, only: [:new, :create]

    def show
        @user = User.find(params[:id])
    end
  
    def index
    end
  
    def new
        @user = User.new
    end
  
    def create
      @user = User.create(user_params)
      if @user.valid?
        @user.save
        session[:user_id] = @user.id
        redirect_to @user
      else
        flash[:error] = "Error, please try to create an account again."
        redirect_to new_user_path
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
    end
  
    private 
    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation, :ruolo)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/home.html.erb
<nav class="navbar navbar-expand-lg bg-danger">
    <div class="container-fluid d-flex">
        <%= link_to "Youtube Manager", root_path, :class => "nav-link navbar-brand" %>
    </div>

    <div class="container-fluid d-flex justify-content-end">
        <%= link_to "Accedi", new_session_path, :class => "btn btn-danger me-1" %>
        <%= link_to "Registrati", new_user_path, :class => "btn btn-danger" %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Progetto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% if flash[:notice] %>
  <%= content_tag :h3, flash[:notice] %>
<% end %>

<%= stylesheet_link_tag "homepage", "data-turbo-track": "reload" %>

<section class="h-100 gradient-form" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
            <div class="col-lg-6">
              <div class="card-body p-md-5 mx-md-4">

                <div class="text-center mb-3">
                    <%= link_to image_tag("https://cdn.cdnlogo.com/logos/y/92/youtube.svg", alt: "logo", style: "width: 185px;"), root_path %>
                </div>

                <%= form_with model: @user do |f| %>
                  <div class="form-floating mb-2">
                    <%= f.text_field :username, :placeholder => "Username", :class => "form-control" %>
                    <label class="form-label" for="form2Example11">Username</label>
                  </div>

                  <div class="form-floating mb-2">
                    <%= f.password_field :password, :placeholder => "Password", :class => "form-control" %>
                    <label class="form-label" for="form2Example22">Password</label>
                  </div>

                  <div class="form-floating mb-2">
                    <%= f.password_field :password_confirmation, :placeholder => "Conferma Password", :class => "form-control" %>
                    <label class="form-label" for="form2Example22">Conferma Password</label>
                  </div>

                  <%= f.select(:ruolo, options_for_select([['Content Creator', 1], ['Manager', 2]]), {}, {class: "form-select mb-3"}) %>

                  <div class="text-center pt-1 mb-5 pb-1 d-grid gap-2">
                    <%= f.submit "Registrati", :class => "btn btn-primary btn-block fa-lg gradient-custom-2 mb-3"%>
                  </div>
                <% end %>
              </div>
            </div>
            
            <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
              <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                <h4 class="mb-4">We are more than just a company</h4>
                <p class="small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                  exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<%= content_tag :h1, current_user.welcome %>
Current user id : <%= current_user.id %>
<%= link_to "Sign Out", sessions_destroy_path(:id => current_user.id), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                  }, :class => "btn btn-danger" %>